### ISSUE TITLE
Collaborative curation

### ISSUE THREAD

**Issue by 8ullyMaguire** [lun-4/awtfdb#57]
I don't understand this program well, but I let this here for consideration, maybe you find some ideas helpful. 

To make awtfdb more collaborative and community-driven, I propose adding the following features:

- Web interface - Allow other users to access the content.

- Collaborative tagging - Allow users to suggest new tags for files which can be voted on by the community. Tags reaching a configurable vote threshold get automatically approved.

- Editable tags - Let users collaboratively create and edit tags, describing their meaning and appropriate usage.

- Tag aliases - Users can suggest tag aliases (different names for the same concept) which get approved through voting. This prevents tag duplication.

- Moderator roles - Designate trusted users as moderators who can review and manually approve pending changes.

- User reputation - Even better than moderator roles than need to be manually applied, allow users to earn reputation points for contributions which unlock abilities like creating tag lists. Like [discourse trust levels](https://blog.discourse.org/2018/06/understanding-discourse-trust-levels).

- Edit histories - Track all changes made to tags, wikis, etc. so edits can be reverted if needed.

Adding these collaborative features would enable users to collectively curate a high-quality and consistent taxonomy. It would also make awtfdb more engaging. Optional permissions could allow users to make their databases fully private if desired.

Here are some additional ideas for increasing participation and engagement using gamification techniques:

- Points system - Users earn points for activities like adding tags, editing tags, reviewing edits, etc. Points can be spent to "buy" rewards like faster downloads, increased limits, custom titles/badges, and more.

- Quests - Daily random quests that give bonus points for completing specific tasks like tagging 10 new files or reviewing 5 pending edits. Keeps users engaged day-to-day.

- Contests - Timed contests for things like most files tagged, most edits reviewed, etc. Top contributors get prizes.

- Leaderboards - Show top contributors over various time ranges (daily, weekly, monthly, all-time). Leaderboard rank earns special badges/titles. 

- Achievements - Users unlock achievements for milestones like total number of tags added, files indexed, days using the platform consecutively, etc.

- Notifications - Send notifications about quests, nearby leaderboard rankings, achievement unlocks, etc. to motivate participation.

- Referrals - Allow users to invite others and earn bonus points when they sign up and contribute.

- Voting - Let users vote on things like new features, wiki edits, tag synonyms/merges, etc. to feel involved.

- Analytics - Provide statistics pages showing individual usage metrics to encourage improving.

Adding these gamified elements on top of the collaborative curation features would really increase awtfdb participation and create a vibrant, engaged user community. The points system would also provide a fair way to ration resources like downloads.

Keywords: MusicBrainz, The Internet Archive, Stash-Box, Image Boards, Hydrus, MediaRepo, Stash, JellyFin, NextCloud, Beets, MusicBrainz Picard, TagSpaces, TagScanner, SpaceDrive, tocc, TMSU, SuperTag, wutag, Tabbles, allTags, Dolphin, ArchiveBox, Lemmy, Reddit, 4chan, Discourse

**Comment by jane0009** [comment]
lol

**Comment by lun-4** [comment]
> To make awtfdb more collaborative and community-driven

that's not a part of my goals

> Web interface - Allow other users to access the content.

the szurubooru backend provides a web interface.

> Collaborative tagging - Allow users to suggest new tags for files which can be voted on by the community. Tags reaching a configurable vote threshold get automatically approved.

this requires a sort of networking system on top of awtfdb. you're better served by hydrus' Public Tag Repository

> Editable tags - Let users collaboratively create and edit tags, describing their meaning and appropriate usage.

tags can't have descriptions, but that's an interesting idea

> Tag aliases - Users can suggest tag aliases (different names for the same concept) which get approved through voting. This prevents tag duplication.

... this already exists.

> Moderator roles - Designate trusted users as moderators who can review and manually approve pending changes.

hydrus PTR

> Edit histories - Track all changes made to tags, wikis, etc. so edits can be reverted if needed.

hydrus PTR

> Adding these collaborative features would enable users to collectively curate a high-quality and consistent taxonomy. It would also make awtfdb more engaging. Optional permissions could allow users to make their databases fully private if desired.

do i actually want to make awtfdb more engaging? you're not doing a good job of convincing me of many ideas, because all you're doing is just firehose a bunch, chatgpt-style.

> Here are some additional ideas for increasing participation and engagement using gamification techniques:

have you used danbooru?

> Adding these gamified elements on top of the collaborative curation features would really increase awtfdb participation and create a vibrant, engaged user community. The points system would also provide a fair way to ration resources like downloads.

i want to [REDACTED]

> Keywords: MusicBrainz, The Internet Archive, Stash-Box, Image Boards, Hydrus, MediaRepo, Stash, JellyFin, NextCloud, Beets, MusicBrainz Picard, TagSpaces, TagScanner, SpaceDrive, tocc, TMSU, SuperTag, wutag, Tabbles, allTags, Dolphin, ArchiveBox, Lemmy, Reddit, 4chan, Discourse

what the fuck.
