### ISSUE TITLE
hypothetical windows support

### ISSUE THREAD

**Issue by jane0009** [lun-4/awtfdb#64]
i understand the primary use case is on *nix based systems, but what would be the major requirements and/or blockers for getting this working on windows? i know zig supports windows out of the box, but i'd imagine a number of the libraries you depend on probably don't.

this is not necessarily asking for it to be implemented as a feature, just wondering if it would be worth it to attempt before i inevitably decide to migrate back to linux full-time

**Comment by lun-4** [comment]
duplicate of https://github.com/lun-4/awtfdb/issues/2

**Comment by jane0009** [comment]
o! mb
